// BlueprintGeneratedClass BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C
// Size: 0x30 (Inherited: 0x30)
struct UBP_Audio_FunctionLibrary_C : UBlueprintFunctionLibrary {

	void Audio_Killer_Footstep_Only_Right_Back(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Only_Right_Back // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Only_Left_Back(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Only_Left_Back // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Generator_Occlusion_Deactivate(struct UAkComponent* AkComponent, struct AActor* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Generator_Occlusion_Deactivate // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Generator_Occlusion_Activate(struct UAkComponent* AkComponent, struct AActor* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Generator_Occlusion_Activate // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Player_LocallyObserved(struct AActor* Player, struct UObject* __WorldContext, bool& IsLocallyObserved); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Player_LocallyObserved // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Hurt_Light_Hooked(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Hurt_Light_Hooked // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Hurt_Light_Wiggle(struct ADBDBasePlayer* Player, struct UObject* __WorldContext, bool& Return Value); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Hurt_Light_Wiggle // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Cloth_ShuffleAttack(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Cloth_ShuffleAttack // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon_Attack_Carry(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon_Attack_Carry // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Haptic_LocallyObserved(struct AActor* Actor, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Haptic_LocallyObserved // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Cloth_Spawning(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Cloth_Spawning // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon_Cooldown(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon_Cooldown // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Scream_Short_K28(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Scream_Short_K28 // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Scream_Long_Mori_K28(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Scream_Long_Mori_K28 // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Dead(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Dead // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Status_Start(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Status_Start // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Stop(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Stop // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Scream_Long_Mori(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Scream_Long_Mori // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Insanity_SnapOfIt(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Insanity_SnapOfIt // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Insanity(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Insanity // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Scream_Hit_Mori(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Scream_Hit_Mori // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Scream_Hit(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Scream_Hit // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Scream_Long(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Scream_Long // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Scream_Scare2d(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Scream_Scare2d // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Scream_Scare(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Scream_Scare // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Hurt_Hard(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Hurt_Hard // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Cough(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Cough // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Hurt_Light(struct ADBDBasePlayer* Player, struct UObject* __WorldContext, bool& Return Value); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Hurt_Light // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Effort_Hard(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Effort_Hard // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt_Effort_Light(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt_Effort_Light // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Status(struct FString AK Audio State, struct ADBDBasePlayer* Player, struct UObject* __WorldContext, struct FString& Audio State); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Status // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Post_AkEvent(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Post_AkEvent // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Footstep_Right(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Footstep_Right // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Footstep_Left(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Footstep_Left // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Grunt(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Grunt // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Survivor_Body(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Survivor_Body // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_K20_Weapon_Scrap(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_K20_Weapon_Scrap // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Surface_Impact(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Surface_Impact // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon_Impact_Survivor(struct ADBDBasePlayer* camper, struct ADBDBasePlayer* Slasher, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon_Impact_Survivor // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon_Impact(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon_Impact // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon_PullOut(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon_PullOut // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon_Clean(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon_Clean // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon_Attack(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon_Attack // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon_Arm(struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon_Arm // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Setup(struct UAkComponent* AudioComponent, struct FName AudioStateKiller, struct UAkAudioEvent* StartEvent, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Setup // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Post_AkEvent(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Post_AkEvent // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Weapon(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Weapon // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Grunt(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Grunt // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Only_Right_Front(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Only_Right_Front // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Only_Right(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Only_Right // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Only_Left_Front(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Only_Left_Front // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Only_Left(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Only_Left // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Right_Front(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Right_Front // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Right(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Right // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Left_Front(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Left_Front // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Footstep_Left(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Footstep_Left // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Cloth_Land(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Cloth_Land // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Cloth_ShuffleLow(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Cloth_ShuffleLow // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Cloth_ShuffleHigh(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Cloth_ShuffleHigh // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void Audio_Killer_Cloth_Move(struct UAkAudioEvent* Ak Audio Event, struct ADBDBasePlayer* Player, struct UObject* __WorldContext); // Function BP_Audio_FunctionLibrary.BP_Audio_FunctionLibrary_C.Audio_Killer_Cloth_Move // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
};

