// BlueprintGeneratedClass VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C
// Size: 0x30 (Inherited: 0x30)
struct UVFX_Function_Lib_AnimNotifies_C : UBlueprintFunctionLibrary {

	bool HandleKillerNotifies_Trickster(struct FName Selection, struct ASlasherPlayer* MySlasher, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Trickster // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	bool HandleKillerNotifies_Blight(struct ASlasherPlayer* My Slasher1, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Blight // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	bool HandleKillerNotifies_Deathslinger(struct ASlasherPlayer* My Slasher1, struct FName Selection, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Deathslinger // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	bool HandleKillerNotifies_Oni(struct UObject* Target, struct UObject* Get Killer1, struct FName Selection, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Oni // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	bool HandleKillerNotifies_Demogorgon(struct FName Selection, struct UObject* Target, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Demogorgon // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	bool HandleKillerNotifies_Nurse(struct FName Selection, struct ASlasherPlayer* My Slasher1, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Nurse // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	bool HandleKillerNotifies_Hag(struct FName Selection, struct ASlasherPlayer* My Slasher1, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Hag // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void HandleKillerNotifies_Trapper(struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Trapper // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	bool HandleKillerNotifies_General(struct ASlasherPlayer* My Slasher1, struct FName Selection, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_General // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	void HandleKillerNotifies_WallBreak(struct FName Selection, struct UObject* WorldContextObject, struct UObject* __WorldContext, bool& Return Value); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_WallBreak // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
	bool HandleKillerNotifies_Footsteps(struct FName Selection, struct ASlasherPlayer* Slasher, struct UObject* __WorldContext); // Function VFX_Function_Lib_AnimNotifies.VFX_Function_Lib_AnimNotifies_C.HandleKillerNotifies_Footsteps // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x5e02c90
};

